### PR TITLE
Add support for the G.722 codec

### LINKED ISSUE #99: G.722WB codec support
Unlinke in Linphone, the G.722WB codec (which has become somewhat become a de facto standard in the recent years) appears to still not being supported by twinkle.
Would it be feasible to incorporate G.722 support in the next twinkle release?
Thank you!
Twinkle is a great client (unlke Linphone :-))

### PR DESCRIPTION
**Pull request by fbriere**
Closes #99

### CODE REVIEW

**Comment by fbriere** [comment]
A word of warning: I was barely able to test this, by confirming that Twinkle could correctly decode what it received from either itself or Asterisk.  That's it.

While the codec itself shouldn't pose much of a problem, some modifications were required deep in the encoding side to account for the discrepancy between the RTP and sampling clock rates.  Bugs are very likely to be present, especially with inband DTMF signaling and 3-way conference calls.  Actual testing from real users would be most welcome!

(At least, I shouldn't have broken *other* codecs.  In theory.)

**Comment by DAC324** [comment]
Last update here on 12 Dec 2019. Are there any new aspects? Is this commit already included in the master branch?

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
Fixes #178

**Comment by fbriere** [comment]
@DAC324 This pull request has not been merged yet (as indicated by its "Open" status icon), due first and foremost to a lack of testing.  The addition of G.722 required some intrusive changes, and the most I can vouch for is that I didn't break anything *else* in the process.  As for the codec itself, well, I did get some sound out of it, so I guess I must've at least done *something* right.  :smile:

Now, we need some real-world testing by actual users, to see if everything works and uncover any bug.  (I've highlighted inband DTMF signaling and 3-way conference calls as areas where bugs are likely.)  Ideally, testing both Twinkle-to-Twinkle and Twinkle-to-something-else connections, to make sure we didn't end up with a dialect of G.722 that is only understood by us.

So, if you are able to give this a try, your help would be most welcome!

(BTW, I have now rebased this PR to include all the bug fixes that were merged recently.  Can't very well test 3-way if that makes Twinkle crash in the first place...)

**Comment by DAC324** [comment]
@fbriere Thank you very much for your efforts and for making this pull request available for testing. As I am not that familiar with git: Can you please advise me on how I can test your version? 
Currently, I am at the master branch - where do I have to go to get your updated version?

**Comment by fbriere** [comment]
@DAC324 I wish GitHub would actually provide an easy and intuitive method for users to check out pull requests.  (sigh)

My recommendation is to use [git-extras](https://github.com/tj/git-extras), already packaged in most distributions.  Then, simply run `git pr 177`, which will create and checkout a new `pr/177` branch with the contents of this pull request.

**Comment by flyingOwl** [comment]
I did tests with two different end points:

- twinkle connected to my Fritz!Box (my landline), calling my (very old) Android phone: twinkle says it uses g722, twinkle can hear the Android phone loud and clear, but the Android phone only gets distorted audio (one can tell THAT something is being said, but not WHAT is being said). This is probably just some handshake or codec negotiation issue not related to this PR.
- twinkle connected to my Fritz!Box, getting a call from my Android phone: twinkle says it uses g711. Everything works fine. But the audio quality at the typical level for g711.
- twinkle connected to my Fritz!Box, calling a (HD voice capable) Fritz!Fon connected to the same Fritz!Box: twinkle says it uses g722, both sides can hear each other loud and clear. One can tell that a wideband audio codec is being used. No issues so far.

**Comment by sjlongland** [comment]
I've been running this branch for a while now… I note it seems to crash if I try to transfer a call, lost a few callers that way.  If I use current `master` branch, I get no issues.

Set up here is:
* Laptop running Gentoo Linux/AMD64, `twinkle` (from `git`) running via JACK
* Netbook running Debian Linux Buster AMD64, `twinkle` (from Debian repositories) running via PulseAudio
* Grandstream HT-814 ATA
* Grandstream GXP1614 desk phone
* Asterisk 1.6 server running on OpenBSD
* Internode NodePhone VoIP as the VSP
* ZTE T84 with SIPDroid
* Codecs enabled in Asterisk: `speex32,g722,speex16,g729,g726,ilbc,speex,alaw,ulaw`

I've found I can make G.722 calls between the ATA, my mobile phone and the desk phone, it works well.  Using G.722 sounds great between the desk-phone, my mobile, the HT-814 or even outbound calls to LTE mobile phones (seems it gets transcoded to whatever VoLTE uses for its wideband CODEC).  However, I've found Twinkle can be a bit unstable at times, causing a segmentation fault in `libasound.so` when transferring calls.

The problem goes away using current `master` branch.  I should probably try re-basing this off `master` and see if that works "better", but right now I'm working on getting Speex to work better since the Asterisk box can transcode as required.

**Comment by sjlongland** [comment]
Just tried a rebase of this branch on `master`: https://github.com/sjlongland/twinkle/tree/feature/g722

I was able to transfer a call reliably with that, guess I'll see if my crash re-occurs with time.

**Comment by fbriere** [comment]
@sjlongland While this PR was initially missing fixes over call transfers (as part of #180), they were all included in the [rebase on March 31](https://github.com/LubosD/twinkle/pull/177#issuecomment-606693359).  Besides, the issues they fixed were deadlocks (i.e. Twinkle freezing), not segfaults.  So, I suspect that the bug you stumbled upon has never been found, let alone fixed.

If you ever manage to trigger it again, would you mind [generating a backtrace](https://github.com/LubosD/twinkle/wiki/Generating-a-backtrace) for us?  That would be quite helpful.  Thanks!

**Comment by sjlongland** [comment]
@fbriere Well, so far so good… I did have a crash after a longish telephone call (incoming)… but yes, I should probably get into the habit of running it under `gdb`.

I'll see about building the relevant bits with debugging symbols and see if I can get a usable stack trace for you.

**Comment by sjlongland** [comment]
@fbriere Silly question, never tried running `twinkle` under `gdb`… is this normal behaviour?

```
RC=0 stuartl@rikishi ~ $ gdb $( which twinkle )
GNU gdb (Gentoo 9.2 vanilla) 9.2
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://bugs.gentoo.org/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/local/bin/twinkle...
(gdb) set logging on
Copying output to gdb.txt.
Copying debug output to gdb.txt.
(gdb) run
Starting program: /usr/local/bin/twinkle 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
[New Thread 0x7ffff1da1700 (LWP 144174)]
[Thread 0x7ffff1da1700 (LWP 144174) exited]
[New Thread 0x7ffff1da1700 (LWP 144175)]
[New Thread 0x7fffeb5ad700 (LWP 144176)]
Language name: "en"
Invalid Context= "Legacy" line for icon theme:  "/usr/share/icons/Adwaita/8x8/legacy/"
Invalid Context= "Legacy" line for icon theme:  "/usr/share/icons/Adwaita/16x16/legacy/"
Invalid Context= "UI" line for icon theme:  "/usr/share/icons/Adwaita/16x16/ui/"
Invalid Context= "Legacy" line for icon theme:  "/usr/share/icons/Adwaita/22x22/legacy/"
Invalid Context= "Legacy" line for icon theme:  "/usr/share/icons/Adwaita/24x24/legacy/"
Invalid Context= "UI" line for icon theme:  "/usr/share/icons/Adwaita/24x24/ui/"
Invalid Context= "Legacy" line for icon theme:  "/usr/share/icons/Adwaita/32x32/legacy/"
Invalid Context= "UI" line for icon theme:  "/usr/share/icons/Adwaita/32x32/ui/"
Invalid Context= "Legacy" line for icon theme:  "/usr/share/icons/Adwaita/48x48/legacy/"
Invalid Context= "UI" line for icon theme:  "/usr/share/icons/Adwaita/48x48/ui/"
Invalid Context= "Legacy" line for icon theme:  "/usr/share/icons/Adwaita/256x256/legacy/"
Invalid Context= "Legacy" line for icon theme:  "/usr/share/icons/Adwaita/512x512/legacy/"
Invalid Context= "UI" line for icon theme:  "/usr/share/icons/Adwaita/scalable/ui/"
[New Thread 0x7fffe2eb5700 (LWP 144177)]
[New Thread 0x7fffe26b4700 (LWP 144178)]
[New Thread 0x7fffe1eb3700 (LWP 144179)]
[New Thread 0x7fffe16b2700 (LWP 144180)]
[New Thread 0x7fffe0eb1700 (LWP 144181)]
[New Thread 0x7fffcbb81700 (LWP 144182)]
[New Thread 0x7fffca2e7700 (LWP 144183)]
[New Thread 0x7fffc9ae6700 (LWP 144184)]
[New Thread 0x7fffc92e5700 (LWP 144185)]
[New Thread 0x7fffc8ae4700 (LWP 144186)]
[New Thread 0x7fffc3fff700 (LWP 144187)]
[New Thread 0x7fffc37fe700 (LWP 144188)]
[New Thread 0x7fffc2ffd700 (LWP 144189)]
[New Thread 0x7fffc27fc700 (LWP 144190)]
[New Thread 0x7fffc1ffb700 (LWP 144191)]
[New Thread 0x7fffc17fa700 (LWP 144192)]
[New Thread 0x7fffc0ff9700 (LWP 144193)]
[New Thread 0x7fffbbfff700 (LWP 144194)]
[New Thread 0x7fffb77fe700 (LWP 144195)]
[Thread 0x7fffb77fe700 (LWP 144195) exited]
[New Thread 0x7fffc82e3700 (LWP 144196)]
[New Thread 0x7fffc8262700 (LWP 144197)]
[New Thread 0x7fffc81e1700 (LWP 144198)]
[New Thread 0x7fffc01a1700 (LWP 144199)]
[New Thread 0x7fffc0120700 (LWP 144200)]

Thread 26 "twinkle" received signal SIG32, Real-time event 32.
[Switching to Thread 0x7fffc81e1700 (LWP 144198)]
0x00007ffff5375859 in syscall () from /lib64/libc.so.6
(gdb) c
Continuing.
[Thread 0x7fffc81e1700 (LWP 144198) exited]

Thread 25 "twinkle" received signal SIG32, Real-time event 32.
[Switching to Thread 0x7fffc8262700 (LWP 144197)]
0x00007ffff7f570ec in read () from /lib64/libpthread.so.0
(gdb) c
Continuing.
[Thread 0x7fffc8262700 (LWP 144197) exited]

Thread 28 "twinkle" received signal SIG32, Real-time event 32.
[Switching to Thread 0x7fffc0120700 (LWP 144200)]
0x00007ffff5375859 in syscall () from /lib64/libc.so.6
(gdb) c
Continuing.
[Thread 0x7fffc0120700 (LWP 144200) exited]

Thread 27 "twinkle" received signal SIG32, Real-time event 32.
[Switching to Thread 0x7fffc01a1700 (LWP 144199)]
0x00007ffff7f570ec in read () from /lib64/libpthread.so.0
(gdb) c
Continuing.
[Thread 0x7fffc01a1700 (LWP 144199) exited]
[Thread 0x7fffc82e3700 (LWP 144196) exited]
[New Thread 0x7fffc82e3700 (LWP 144203)]
[New Thread 0x7fffc01a1700 (LWP 144204)]
[New Thread 0x7fffc0120700 (LWP 144205)]
[New Thread 0x7fffc8262700 (LWP 144206)]
[New Thread 0x7fffc81e1700 (LWP 144208)]

Thread 31 "twinkle" received signal SIG32, Real-time event 32.
[Switching to Thread 0x7fffc0120700 (LWP 144205)]
0x00007ffff5375859 in syscall () from /lib64/libc.so.6
(gdb) c
Continuing.
[Thread 0x7fffc0120700 (LWP 144205) exited]

Thread 30 "twinkle" received signal SIG32, Real-time event 32.
[Switching to Thread 0x7fffc01a1700 (LWP 144204)]
0x00007ffff7f570ec in read () from /lib64/libpthread.so.0
(gdb) c
Continuing.
[Thread 0x7fffc01a1700 (LWP 144204) exited]

Thread 33 "twinkle" received signal SIG32, Real-time event 32.
[Switching to Thread 0x7fffc81e1700 (LWP 144208)]
0x00007ffff5375859 in syscall () from /lib64/libc.so.6
(gdb) c
Continuing.
[Thread 0x7fffc81e1700 (LWP 144208) exited]

Thread 32 "twinkle" received signal SIG32, Real-time event 32.
[Switching to Thread 0x7fffc8262700 (LWP 144206)]
0x00007ffff7f570ec in read () from /lib64/libpthread.so.0
(gdb) c
Continuing.
[Thread 0x7fffc8262700 (LWP 144206) exited]
[Thread 0x7fffc82e3700 (LWP 144203) exited]
[New Thread 0x7fffb77fe700 (LWP 144211)]
```

It's running now, but I had to tell it to `continue` numerous times before it got going and popped up a dialogue box.  I'll be in a position to catch the backtrace if it crashes.  Just seems odd that it kept halting with "Real-time event 32" signal messages before it got started in earnest.

For the record: build options are: `-DWITH_QT5=On -DWITH_ZRTP=Off -DWITH_G729=On -DWITH_SPEEX=On -DWITH_ILBC=Off -DCMAKE_BUILD_TYPE=Debug`

**Comment by fbriere** [comment]
@sjlongland Apparently, [glibc uses `SIG32` to signal the cancellation of threads](https://gnobal.net/591/what-is-sig32-during-a-gdb-debug-session).  You can tell GDB to ignore these with `handle SIG32 nostop` (or `noprint` to do it silently — see the [Signals section of the GDB manual](https://sourceware.org/gdb/current/onlinedocs/gdb/Signals.html) for more details).

I know I looked into this some time ago, but I can't remember why I didn't take good note of it.  Anyway, I'll make sure to add this to the Wiki page (along with `set pagination off` to get rid of the pager).  Thanks for the reminder!

**Comment by DAC324** [comment]
> My recommendation is to use [git-extras](https://github.com/tj/git-extras), already packaged in most distributions. Then, simply run `git pr 177`, which will create and checkout a new `pr/177` branch with the contents of this pull request.

This does not seem to work here:
`$ git pr 177
fatal: Could not find remote reference refs/pull/177/head`

**Comment by DAC324** [comment]
> Just tried a rebase of this branch on `master`: https://github.com/sjlongland/twinkle/tree/feature/g722
> 
> I was able to transfer a call reliably with that, guess I'll see if my crash re-occurs with time.

How do I enable G.722 in that version? It does not seem to appear under Available Codecs.

**Comment by DAC324** [comment]
Don't take it amiss but I am giving up on Twinkle now.
Apart from the missing G.722 codec in this version, it also seems to be unable to connect to my router anymore. It simply gives "408 Timeout" so I cannot dial any numbers anymore. 
As other programs (Empathy, LinPhone) work with the very same server settings I also used for Twinkle, I have to consider the program broken, at least for me.

**Comment by sjlongland** [comment]
On 14/9/20 11:27 pm, DAC324 wrote:
>> Just tried a rebase of this branch on `master`: https://github.com/sjlongland/twinkle/tree/feature/g722
>>
>> I was able to transfer a call reliably with that, guess I'll see if my crash re-occurs with time.
> 
> How do I enable G.722 in that version? It does not seem to appear under Available Codecs.
> 

It was automatic for me… I'll double check.  Maybe there's a library you
need to enable G.722?

**Comment by sjlongland** [comment]
`CMakeCache.txt` has:
```
//Enable ALSA support
WITH_ALSA:BOOL=ON

//Enable use of QtDBus (GUI only)
WITH_DBUS:BOOL=ON

//Enable Diamondcard integration
WITH_DIAMONDCARD:BOOL=OFF

//Enable G.729A support
WITH_G729:BOOL=On

//Use external GSM library
WITH_GSM:BOOL=OFF

//Enable the iLBC codec
WITH_ILBC:BOOL=Off

//Enable Qt 5 GUI
WITH_QT5:BOOL=On

//Enable the Speex codec
WITH_SPEEX:BOOL=On

//Enable ZRTP encrypted calls
WITH_ZRTP:BOOL=Off
```

I see this in my audio settings:
twinkle-g722

**Comment by fbriere** [comment]
@DAC324 Sorry to see you go.  I hope you do find a program that will suit your needs.

I'll still address the points you raised nonetheless, in case this can be useful to others, or if you ever decide to give Twinkle a second chance.

**Comment by fbriere** [comment]
> This does not seem to work here:
> 
> $ git pr 177
> fatal: Could not find remote reference refs/pull/177/head
>
> So I tried that a bit differently:
> 
> $git clone https://github.com/fbriere/twinkle.git

Pull requests are only available in the central repo (https://github.com/LubosD/twinkle.git), not in my own personal fork.

> Reading through this thread, I then tried https://github.com/sjlongland/twinkle.git - but the result is the same. The G.722 codec does not appear.

When cloning with SSH or HTTPS, the checked-out branch will always be the main branch (typically `master`) by default, regardless of what branch was displayed on the page where you got the clone URL.  (I wish GitHub added a note about this.)  You then need to switch to this branch manually with `git checkout feature/g722`.  (You can also combine both steps by adding `--branch feature/g722` to the `clone` command line.)

**Comment by sjlongland** [comment]
```
Thread 143 "twinkle" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffc8118700 (LWP 118608)]
0x00007ffff78ce28c in snd_pcm_areas_copy () from /usr/lib64/libasound.so.2
```

[gdb.txt](https://github.com/LubosD/twinkle/files/5242990/gdb.txt)

**Comment by sjlongland** [comment]
Looking at that backtrace, it would appear Twinkle managed to tickle the ALSA JACK plug-in the wrong way.

**Comment by fbriere** [comment]
> ```
> Thread 143 "twinkle" received signal SIGSEGV, Segmentation fault.
> [Switching to Thread 0x7fffc8118700 (LWP 118608)]
> 0x00007ffff78ce28c in snd_pcm_areas_copy () from /usr/lib64/libasound.so.2
> ```

Meanwhile, thread 1 was apparently busy tearing this down with `snd_pcm_hw_free()` after the call was ended.  Maybe a race condition between the two?

We'll definitely need symbols for `libjack.so` before we can dig any further.  Would you mind installing those and generating another backtrace?  (If you don't have a core file ready, you may want to use [`generate-core-file`](https://sourceware.org/gdb/onlinedocs/gdb/Core-File-Generation.html) next time.)

**Comment by sjlongland** [comment]
Yep, no problems, I'll see if I can build `libasound.so` with debugging symbols as well.

**Comment by sjlongland** [comment]
[gdb-20200919.txt](https://github.com/LubosD/twinkle/files/5248195/gdb-20200919.txt)

```
0x00007ffff78cf28c in snd_pcm_areas_copy (dst_areas=dst_areas@entry=0x555556099280, dst_offset=dst_offset@entry=0, src_areas=src_areas@entry=0x0, src_offset=src_offset@entry=0, channels=channels@entry=2, frames=frames@entry=1024, format=SND_PCM_FORMAT_FLOAT_LE) at /var/tmp/portage/media-libs/alsa-lib-1.2.2-r1/work/alsa-lib-1.2.2/src/pcm/pcm.c:3322
3322    /var/tmp/portage/media-libs/alsa-lib-1.2.2-r1/work/alsa-lib-1.2.2/src/pcm/pcm.c: No such file or directory.
(gdb) bt
#0  0x00007ffff78cf28c in snd_pcm_areas_copy (dst_areas=dst_areas@entry=0x555556099280, dst_offset=dst_offset@entry=0, src_areas=src_areas@entry=0x0, src_offset=src_offset@entry=0, channels=channels@entry=2, frames=frames@entry=1024, format=SND_PCM_FORMAT_FLOAT_LE) at /var/tmp/portage/media-libs/alsa-lib-1.2.2-r1/work/alsa-lib-1.2.2/src/pcm/pcm.c:3322
#1  0x00007ffff78cf4a7 in snd_pcm_areas_copy_wrap (dst_channels=0x555556099280, dst_offset=dst_offset@entry=0, dst_size=dst_size@entry=1024, src_channels=0x0, src_offset=0, src_size=9216, channels=2, frames=1024, format=SND_PCM_FORMAT_FLOAT_LE) at /var/tmp/portage/media-libs/alsa-lib-1.2.2-r1/work/alsa-lib-1.2.2/src/pcm/pcm.c:3403
#2  0x00007fffe887c5f7 in snd_pcm_jack_process_cb (nframes=<optimized out>, io=0x555555f61ff0) at /var/tmp/portage/media-plugins/alsa-plugins-1.2.2/work/alsa-plugins-1.2.2/jack/pcm_jack.c:232
#3  0x00007fffd8368d0a in Jack::JackClient::ExecuteThread() () from /usr/lib64/libjack.so.0
#4  0x00007fffd8368478 in Jack::JackClient::Execute() () from /usr/lib64/libjack.so.0
#5  0x00007fffd83810cc in Jack::JackPosixThread::ThreadHandler(void*) () from /usr/lib64/libjack.so.0
#6  0x00007ffff7f4def7 in start_thread () from /lib64/libpthread.so.0
#7  0x00007ffff557dcbf in clone () from /lib64/libc.so.6

Thread 1 (Thread 0x7ffff21a8780 (LWP 245831)):
#0  0x00007ffff55733cf in poll () from /lib64/libc.so.6
#1  0x00007ffff43c068e in ?? () from /usr/lib64/libglib-2.0.so.0
#2  0x00007ffff43c07af in g_main_context_iteration () from /usr/lib64/libglib-2.0.so.0
#3  0x00007ffff5cd9d0e in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib64/libQt5Core.so.5
#4  0x00007ffff5c84cdb in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib64/libQt5Core.so.5
#5  0x00007ffff5c8caa2 in QCoreApplication::exec() () from /usr/lib64/libQt5Core.so.5
#6  0x000055555580074f in t_gui::run (this=0x555555c56360) at /home/stuartl/projects/twinkle/src/gui/gui.cpp:924
#7  0x000055555582179e in main (argc=1, argv=0x7fffffffd198) at /home/stuartl/projects/twinkle/src/gui/main.cpp:1046
```

A crash for a different reason this time… but I'll keep working at the other.  Seems the crash I saw before seems to happen at the end of a call.  I tried ringing a few times from my ATA through the Asterisk system to Twinkle, but didn't get any bites.  One thought is that maybe it's transcoding in the Asterisk box triggering this (crashes due to outside calls) and I'm not triggering it internally because the ATA does G.722 natively, so I might try again with Twinkle on Debian (which is NOT compiled with G.722), although transcoding is a bit of a stretch, since JACK shouldn't care either way (it should be seeing signed linear PCM at this point).

**Comment by sjlongland** [comment]
Okay, hypothesis time… so it's copying PCM data around in another thread, when we suddenly tell it to "free" the PCM channel.

```
t_alsa_io::~t_alsa_io() {
	if (pcm_play_ptr) {
		log_file->write_header("t_alsa_io::~t_alsa_io", LOG_NORMAL, LOG_DEBUG);
		log_file->write_raw("snd_pcm_close, handle = ");
		log_file->write_raw(ptr2str(pcm_play_ptr));
		log_file->write_endl();
		log_file->write_footer();
		
		// Without the snd_pcm_hw_free, snd_pcm_close sometimes fails.
		snd_pcm_hw_free(pcm_play_ptr); /* ← crash is here */
		snd_pcm_close(pcm_play_ptr);
		pcm_play_ptr = 0;
	}
	if (pcm_rec_ptr) {
		log_file->write_header("t_alsa_io::~t_alsa_io", LOG_NORMAL, LOG_DEBUG);
		log_file->write_raw("snd_pcm_close, handle = ");
		log_file->write_raw(ptr2str(pcm_rec_ptr));
		log_file->write_endl();
		log_file->write_footer();
		
		snd_pcm_hw_free(pcm_rec_ptr);
		snd_pcm_close(pcm_rec_ptr);
		pcm_rec_ptr = 0;
	}
}
```

https://www.alsa-project.org/alsa-doc/alsa-lib/group___p_c_m.html#ga49afc5b8527f30c33fafa476533c9f86

Should we be calling either `snd_pcm_drain` or `snd_pcm_drop` prior to doing this?  (Maybe `…_drop`, since we're in a destructor.)

**Comment by sjlongland** [comment]
https://github.com/sjlongland/twinkle/commit/0afff6ab170c97000fc404210e05de8494ad3af9 ← made a small tweak, let's see what this does.

**Comment by fbriere** [comment]
> Yep, no problems, I'll see if I can build `libasound.so` with debugging symbols as well.

Thanks!  This seems to be where the bug lies: `snd_pcm_jack_process_cb()` doesn't check the return value of `snd_pcm_ioplug_mmap_areas()` before passing it to `snd_pcm_areas_copy_wrap()`.  After things have been torn down, that value is now `NULL`, and hilarity ensues.

**Comment by fbriere** [comment]
> Thanks! This seems to be where the bug lies: `snd_pcm_jack_process_cb()` doesn't check the return value of `snd_pcm_ioplug_mmap_areas()` before passing it to `snd_pcm_areas_copy_wrap()`. After things have been torn down, that value is now `NULL`, and hilarity ensues.

Sounds similar to alsa-project/alsa-plugins#11, come to think of it...

**Comment by sjlongland** [comment]
@fbriere Yeah it does, but looking at the stack trace, it seems the rug is getting pulled out from underneath one of the threads, hence it crashes to the ground.

Now, when I read the docs, it says that both `snd_pcm_drain` and `snd_pcm_drop` functions cause the stream to "stop" (one immediately, discarding samples, the other after draining the buffer)… and to me, that seems like a common-sense thing to do: tell the underlying driver that "the stream is going away real soon now" *then* free its memory.  Freeing a stream without first stopping it sounds like playing with fire to me.

So far, I've not had any crashes with that two-line patch.

**Comment by DAC324** [comment]
> When cloning with SSH or HTTPS, the checked-out branch will always be the main branch (typically `master`) by default, regardless of what branch was displayed on the page where you got the clone URL. (I wish GitHub added a note about this.) You then need to switch to this branch manually with `git checkout feature/g722`. (You can also combine both steps by adding `--branch feature/g722` to the `clone` command line.)

Looks like I am missing something here:
<pre>
git clone https://github.com/LubosD/twinkle.git --branch feature/g722
Cloning into 'twinkle'...
fatal: Remote branch feature/g722 not found in upstream origin
[gerd@gerd-desktop Downloads]$ git clone https://github.com/LubosD/twinkle.git
Cloning into 'twinkle'...
remote: Enumerating objects: 110, done.
remote: Counting objects: 100% (110/110), done.
remote: Compressing objects: 100% (80/80), done.
remote: Total 3389 (delta 69), reused 51 (delta 30), pack-reused 3279
Receiving objects: 100% (3389/3389), 3.07 MiB | 5.50 MiB/s, done.
Resolving deltas: 100% (2373/2373), done.
[gerd@gerd-desktop Downloads]$ git checkout feature/g722
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
[gerd@gerd-desktop Downloads]$ cd twinkle
[gerd@gerd-desktop twinkle]$ git checkout feature/g722
error: pathspec 'feature/g722' did not match any file(s) known to git
[gerd@gerd-desktop twinkle]$ 
</pre>

**Comment by sjlongland** [comment]
Try:

`git clone https://github.com/fbriere/twinkle.git --branch feature/g722`

Or if you want my version:
`git clone https://github.com/sjlongland/twinkle.git --branch feature/g722`

**Comment by symptog** [comment]
I'm using the branch from fbriere for almost 2 months without any issues :+1:

**Review by sss545 — APPROVED** [review]
Hyy

**Pull request merged**
